spring:
  datasource:
    url: jdbc:mysql//localhost:3306/sfg_dev
    data-username: sfg_dev_user
    data-password: guru
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true