spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    data-username: sfg_prod_user
    data-password: guru
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
